function downloadCSV(data) {
  const timestamp = new Date().toISOString().slice(0, 19).replace('T', ' ');

  const rows = [];

  rows.push(`"Dashboard Export - ${timestamp}"`);
  rows.push('');

  rows.push('"KPI Metrics","Value"');
  rows.push(`"Total Users",${data.totalUsers}`);
  rows.push(`"Revenue (USD)",${data.revenue}`);
  rows.push(`"Growth Rate (%)",${data.growthRate}`);
  rows.push(`"Active Users",${data.activeUsers}`);
  rows.push('');

  rows.push('"Revenue History (Last 8)","Amount (USD)"');
  data.revenueHistory.forEach((val, index) => {
    rows.push(`"Point ${index + 1}",${val}`);
  });
  rows.push('');

  rows.push('"Feature","Usage Count"');
  data.featureUsage.forEach(item => {
    rows.push(`"${item.name}",${item.value}`);
  });
  rows.push('');

  rows.push('"User Segment","Count"');
  rows.push(`"Free Users",${data.segmentation.free}`);
  rows.push(`"Premium Users",${data.segmentation.premium}`);
  rows.push('');

  rows.push('"Report generated by Analytics Dashboard"');

  const csvString = rows.join('\n');

  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.href = url;
  link.setAttribute('download', `dashboard_export_${Date.now()}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}